### ISSUE TITLE
solidity-lib 2.8.0

### ISSUE THREAD

**Issue by Arvolear** [dl-solarity/solidity-lib#91]
### Potential list of tasks

- [x] Memory utils library
- [x] Refactor `StringSet` to `DynamicSet`
- [x] AVL data structure
- [ ] EdDSA signature verification 
- [ ] BigInt library
- [ ] Fix presets (initializer function -> internal `onlyInitializing`)
- [ ] Optimized array (3 address elements use 2 slots)
- [ ] Protocol-wide pausable/reentrancy guards
- [ ] ContractsRegistry versionable
- [ ] Major optimization of code
- [ ] `UniswapV2Oracle` upgrade. Support multiple paths for the same tokens (return an array of prices). Support `bestPrice(in, out)` method
